### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mightyiam** [rowanmanning/proclaim#21]
I'm still writing code for IE8.

Proclaim is awesome.

Thanks to the aliases, it was a [100% drop in](https://github.com/PolicyStat/combokeys/pull/37).

The PR doesn't show that it is a 100% drop in but it was.

I've rewritten from `chai.expect` to `chai.assert` before (re)discovering that `chai.assert` requires IE >= 9.

After that, it was just a matter of changing `var assert = require('chai').assert` to `var assert = require('proclaim')` and swoosh! It wall went smoothly!

**Comment by rowanmanning** [comment]
Aw I'm glad you found it useful :) it's good to hear!
