### ISSUE TITLE
Presence of RequireJS blocks global definition

### ISSUE THREAD

**Issue by dustinlarimer** [rowanmanning/proclaim#22]
Found a minor snag where the export logic on [L540](https://github.com/rowanmanning/proclaim/blob/master/lib/proclaim.js#L540) blocks the library from being defined globally when RequireJS is present. We test our libraries with the presence of RequireJS, since we're often loaded as a 3rd party vendor script in environments that our users can't always predict or control. Would it be possible to break this out of the current either/or condition?

Thanks for building this project.. I've also been super frustrated with lack of legacy IE support by alternate assertion libraries. Excited to take this for a spin :)

**Comment by rowanmanning** [comment]
Hi Dustin, so are you suggesting always add proclaim to root? I'd consider this but might have to provide a `noConflict` method similar to jQuery. I've been thinking about doing this anyway.

**Comment by dustinlarimer** [comment]
@rowanmanning yup, that's the idea.. we decoupled these in our lib and just define wherever/however appropriate: https://github.com/keen/keen-js/blob/master/src/keen.js#L3

**Comment by dustinlarimer** [comment]
@rowanmanning if you're open to this, I'd be more than happy to make a PR.

**Comment by rowanmanning** [comment]
Hi, sorry for the slack reply. I started working on this actually and have it running locally, just need to publish when I get back to my machine. Thanks for the offer!

**Comment by dustinlarimer** [comment]
No worries, and I'm happy to hear that - thank you!

**Comment by rowanmanning** [comment]
Hey @dustinlarimer, does this solve your issue? https://github.com/rowanmanning/proclaim/commit/0ca279713066226fc299131b5029195b66d6490a - new version (3.3.0) released.

**Comment by dustinlarimer** [comment]
@rowanmanning works perfectly – thanks!
