### ISSUE TITLE
Error reporting on DomElements

### ISSUE THREAD

**Issue by alicebartlett** [rowanmanning/proclaim#46]
Test case:

```js
var myElement = document.querySelectorAll(body);
proclaim.notStrictEqual(myElement, myElement);
```

^^This should return a fail, but instead the error reporter appears to timeout when tasked with reporting any element. 
By contrast, the following test passes and no timeout occurs.

```js
var myElement = document.querySelectorAll(body);
proclaim.strictEqual(myElement, myElement);
```

**Comment by rowanmanning** [comment]
Just trying to work out what's causing this. Haven't been able to replicate in-browser. Using this: https://jsbin.com/sosikogeyu/edit?js,console
