### ISSUE TITLE
proclaim.includes not working on special objects such as `window`

### ISSUE THREAD

**Issue by JakeChampion** [rowanmanning/proclaim#47]
Reproducible test case -- https://jsbin.com/tevapoyucu/edit?html,js,console,output

I believe this occurs because the `isPlainObject` function returns false for objects such as `window`.

I'm not too sure how we should go about solving this issue. For the moment I am working around this by using `proclaim.ok(Object.prototype.hasOwnProperty.call(window, 'document'))`.

**Comment by rowanmanning** [comment]
Reckon we might just be able to change [this line](https://github.com/rowanmanning/proclaim/blob/master/lib/proclaim.js#L368):

```diff
// Object#hasOwnProperty
- if (isPlainObject(haystack)) {
+ if (typeof haystack === 'object' && haystack !== null) {
    if (haystack.hasOwnProperty(needle)) {
        return true;
    }
}
```
